import type { OrganizerLanguage } from "./user-config";

const english = {
  addChild: "Add a child-node", addChildNode: "Add child-node", addChildren: "Add child-nodes", addNode: "Add node", alreadyCurrent: "{name} is already the current level.", alreadyFirstLevel: "{name} is already at the first level.",
  cancelNewMap: "Cancel new map", childCountOne: "1 child", childCountMany: "{count} children", close: "Close", closeMapList: "Close map list", completeGraphView: "Complete graph view.", completeProjectGraph: "Complete map graph", confirmMapName: "Confirm map name", contextualShortcuts: "Contextual keyboard shortcuts",
  connectedChoice: " Connected choice {current} of {total}.", copied: "The complete element text was copied.", copiedToast: "Copied to clipboard", copyFailed: "The element text could not be copied.", copyFailedToast: "Could not copy to clipboard",
  copyName: "Copy name", copyElementName: "Copy element name", createMap: "Create map", created: "{name} was created.", currentLevel: "{name} level.", currentLevelCannotRemove: "The current level cannot be removed here.", currentLocation: "Current location", currentNode: "{name} is now the current node.", darkEnabled: "Dark mode enabled.",
  delete: "Delete", deleteElement: "Delete element", deleteMap: "Delete map", deletedMap: "{name} deleted.", displayMode: "Display mode", duplicate: "Duplicate", duplicateMap: "Duplicate map", edit: "Edit", editCancelled: "Edit cancelled.", editElement: "Edit node", editElementAction: "Edit element", editing: "Editing {name}. Type a name and press Enter.", editName: "Edit name", editMapName: "Edit map name", element: "Element", elementActions: "Element actions", elementSelected: "{name} is selected.",
  depthLimitMessage: "It looks like we've reached the maximum depth of {count} levels. You can't add any more child-nodes.", depthLimitTitle: "Maximum depth reached", export: "Export", exportMap: "Export map", exported: "{name} exported.", goBack: "Go up one level", goUpOneLevel: "Go up one level", graphView: "Graph view", languageSelector: "Language", lightEnabled: "Light mode enabled.", loading: "Loading your organizer…", loaded: "{name} loaded.", move: "Move", movedUp: "{name} moved up one level.",
  newElementCancelled: "New element cancelled.", newElementReady: "New element ready. Type a name and press Enter.", newMap: "New map", newMapCancelled: "New map cancelled.", newMapReady: "New map created. Enter its name and confirm it.", noPreviousSibling: "This element has no previous sibling-node to become its parent-node.", nodeLevel: "{name}, level {level}", nowChildOf: "{name} is now a child-node of {parent}.", nowCurrentLevel: "{name} is now the current level.", openNode: "Open node", opened: "{name} opened.", openMapList: "Open map list", openAndAddChild: "Open {name} and add a child-node", mapNameRequired: "Enter a map name before confirming.",
  projectTree: "Map tree view", removeRoot: "The root element cannot be removed.", removed: "{name} and its nested elements were removed.", renamed: "{name} was renamed.", returnedTo: "Returned to {name}.", rootCannotMove: "The root cannot be moved up.", saveError: "Changes are not being saved. Browser storage may be unavailable or full. Export important maps before closing this tab.",
  shortcutAddSibling: "Add sibling", shortcutIndent: "Indent node", shortcutOutdent: "Move node up", switchToDark: "Use dark mode", switchToEnglish: "Switch to English", switchToLight: "Use light mode", switchToSpanish: "Switch to Spanish", languageEnglishEnabled: "English selected.", languageSpanishEnabled: "Spanish selected.", topLevel: "{name} is the top level.", mapActions: "Map actions", mapList: "Maps", mapText: "Map text", treeView: "Tree view", treeViewReady: "Tree view ready. Enter adds a sibling-node; Tab indents.", tutorialOpened: "Tutorial opened.", untitledMap: "Untitled map", viewNode: "View node", voronoiLevel: "{name} level", voronoiView: "Voronoi view", editorEdit: "Edit element text", editorNew: "New element text",
} as const;

export type TranslationKey = keyof typeof english;

const spanish: Record<TranslationKey, string> = {
  addChild: "Añadir un nodo-hijo", addChildNode: "Añadir nodo-hijo", addChildren: "Añadir nodos-hijo", addNode: "Añadir nodo", alreadyCurrent: "{name} ya es el nivel actual.", alreadyFirstLevel: "{name} ya está en el primer nivel.",
  cancelNewMap: "Cancelar mapa nuevo", childCountOne: "1 hijo", childCountMany: "{count} hijos", close: "Cerrar", closeMapList: "Cerrar lista de mapas", completeGraphView: "Vista de grafo completa.", completeProjectGraph: "Grafo completo del mapa", confirmMapName: "Confirmar nombre del mapa", contextualShortcuts: "Atajos de teclado contextuales",
  connectedChoice: " Opción conectada {current} de {total}.", copied: "Se copió el texto completo del elemento.", copiedToast: "Copiado al portapapeles", copyFailed: "No se pudo copiar el texto del elemento.", copyFailedToast: "No se pudo copiar al portapapeles",
  copyName: "Copiar nombre", copyElementName: "Copiar nombre del elemento", createMap: "Crear mapa", created: "Se creó {name}.", currentLevel: "Nivel de {name}.", currentLevelCannotRemove: "El nivel actual no se puede eliminar aquí.", currentLocation: "Ubicación actual", currentNode: "{name} es ahora el nodo actual.", darkEnabled: "Modo oscuro activado.",
  delete: "Eliminar", deleteElement: "Eliminar elemento", deleteMap: "Eliminar mapa", deletedMap: "Se eliminó {name}.", displayMode: "Modo de visualización", duplicate: "Duplicar", duplicateMap: "Duplicar mapa", edit: "Editar", editCancelled: "Edición cancelada.", editElement: "Editar nodo", editElementAction: "Editar elemento", editing: "Editando {name}. Escribe un nombre y presiona Enter.", editName: "Editar nombre", editMapName: "Editar nombre del mapa", element: "Elemento", elementActions: "Acciones del elemento", elementSelected: "{name} está seleccionado.",
  depthLimitMessage: "Parece que hemos llegado a la profundidad máxima de {count} niveles. No se pueden añadir más nodos-hijo.", depthLimitTitle: "Profundidad máxima alcanzada", export: "Exportar", exportMap: "Exportar mapa", exported: "Se exportó {name}.", goBack: "Subir un nivel", goUpOneLevel: "Subir un nivel", graphView: "Vista Grafo", languageSelector: "Idioma", lightEnabled: "Modo claro activado.", loading: "Cargando tu organizador…", loaded: "{name} cargado.", move: "Mover", movedUp: "{name} subió un nivel.",
  newElementCancelled: "Nuevo elemento cancelado.", newElementReady: "Nuevo elemento listo. Escribe un nombre y presiona Enter.", newMap: "Nuevo mapa", newMapCancelled: "Nuevo mapa cancelado.", newMapReady: "Nuevo mapa creado. Escribe su nombre y confírmalo.", noPreviousSibling: "Este elemento no tiene un nodo-hermano anterior que pueda convertirse en su nodo-padre.", nodeLevel: "{name}, nivel {level}", nowChildOf: "{name} es ahora un nodo-hijo de {parent}.", nowCurrentLevel: "{name} es ahora el nivel actual.", openNode: "Abrir nodo", opened: "Se abrió {name}.", openMapList: "Abrir lista de mapas", openAndAddChild: "Abrir {name} y añadir un nodo-hijo", mapNameRequired: "Escribe un nombre para el mapa antes de confirmar.",
  projectTree: "Vista de árbol del mapa", removeRoot: "El elemento raíz no se puede eliminar.", removed: "Se eliminaron {name} y sus elementos anidados.", renamed: "Se cambió el nombre de {name}.", returnedTo: "Se volvió a {name}.", rootCannotMove: "La raíz no se puede subir.", saveError: "Los cambios no se están guardando. El almacenamiento del navegador puede no estar disponible o estar lleno. Exporta los mapas importantes antes de cerrar esta pestaña.",
  shortcutAddSibling: "Añadir hermano", shortcutIndent: "Anidar nodo", shortcutOutdent: "Subir nodo", switchToDark: "Usar modo oscuro", switchToEnglish: "Cambiar a inglés", switchToLight: "Usar modo claro", switchToSpanish: "Cambiar a español", languageEnglishEnabled: "Inglés seleccionado.", languageSpanishEnabled: "Español seleccionado.", topLevel: "{name} es el nivel superior.", mapActions: "Acciones del mapa", mapList: "Mapas", mapText: "Texto del mapa", treeView: "Vista Árbol", treeViewReady: "Vista Árbol lista. Enter añade un hermano; Tab anida.", tutorialOpened: "Tutorial abierto.", untitledMap: "Mapa sin título", viewNode: "Ver nodo", voronoiLevel: "Nivel de {name}", voronoiView: "Vista Voronoi", editorEdit: "Editar texto del elemento", editorNew: "Texto del nuevo elemento",
};

export const translations: Record<OrganizerLanguage, Record<TranslationKey, string>> = { en: english, es: spanish };

export function translate(language: OrganizerLanguage, key: TranslationKey, values: Record<string, string | number> = {}): string {
  return Object.entries(values).reduce((message, [name, value]) => message.replaceAll(`{${name}}`, String(value)), translations[language][key]);
}
